In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'3.0.3'

In [4]:
data = pd.read_csv("credit_card_fraud_10k.csv")

In [10]:
data.head(10)

,transaction_id,amount,transaction_hour,merchant_category,foreign_transaction,location_mismatch,device_trust_score,velocity_last_24h,cardholder_age,is_fraud
0,1,84.47,22,Electronics,0,0,66,3,40,0
1,2,541.82,3,Travel,1,0,87,1,64,0
2,3,237.01,17,Grocery,0,0,49,1,61,0
3,4,164.33,4,Grocery,0,1,72,3,34,0
4,5,30.53,15,Food,0,0,79,0,44,0
5,6,30.53,13,Clothing,0,0,90,2,46,0
6,7,10.77,18,Travel,0,0,48,1,28,0
7,8,362.02,13,Electronics,0,0,68,1,40,0
8,9,165.43,8,Grocery,0,0,80,0,21,0
9,10,221.63,5,Grocery,0,0,59,1,34,0

In [11]:
data.columns

Index(['transaction_id', 'amount', 'transaction_hour', 'merchant_category',
       'foreign_transaction', 'location_mismatch', 'device_trust_score',
       'velocity_last_24h', 'cardholder_age', 'is_fraud'],
      dtype='str')

In [12]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   transaction_id       10000 non-null  int64
 1   amount               10000 non-null  float64
 2   transaction_hour     10000 non-null  int64
 3   merchant_category    10000 non-null  str
 4   foreign_transaction  10000 non-null  int64
 5   location_mismatch    10000 non-null  int64
 6   device_trust_score   10000 non-null  int64
 7   velocity_last_24h    10000 non-null  int64
 8   cardholder_age       10000 non-null  int64
 9   is_fraud             10000 non-null  int64
dtypes: float64(1), int64(8), str(1)
memory usage: 781.4 KB

In [13]:
data.shape

(10000, 10)

In [14]:
"""Deleting redundant columns.
Renaming the columns.
Dropping duplicates.
Remove the NaN values from the dataset
Cleaning individual columns.
Check for some more Trnasformations"""

'Deleting redundant columns.\nRenaming the columns.\nDropping duplicates.\nRemove the NaN values from the dataset\nCleaning individual columns.\nCheck for some more Trnasformations'

In [15]:
data.columns

Index(['transaction_id', 'amount', 'transaction_hour', 'merchant_category',
       'foreign_transaction', 'location_mismatch', 'device_trust_score',
       'velocity_last_24h', 'cardholder_age', 'is_fraud'],
      dtype='str')

In [41]:
columns_to_keep = ['transaction_hour', 'merchant_category']
columns_to_drop = ['transaction_id', 'amount','cardholder_age', 'is_fraud']

In [42]:
data.shape

(10000, 2)

In [43]:
len(columns_to_keep)

2

In [44]:
len(columns_to_drop)

4

# 1st Way - Filtering Data

In [45]:
columns_to_keep

['transaction_hour', 'merchant_category']

In [46]:
modify_data = data[columns_to_keep]

In [34]:
modify_data

      transaction_hour merchant_category
0                   22       Electronics
1                    3            Travel
2                   17           Grocery
3                    4           Grocery
4                   15              Food
...                ...               ...
9995                22              Food
9996                 5          Clothing
9997                21       Electronics
9998                 2       Electronics
9999                 2          Clothing

[10000 rows x 2 columns]

# 2nd way,dropping the columns

In [47]:
columns_to_drop

['transaction_id', 'amount', 'cardholder_age', 'is_fraud']

In [11]:
import pandas as pd

data = pd.read_csv("credit_card_fraud_10k.csv")

In [12]:
columns_to_drop = ['transaction_id', 'amount', 'cardholder_age', 'is_fraud']

data = data.drop(columns=columns_to_drop, errors='ignore')

In [60]:
"""Deleting redundant columns.
Renaming the columns.
Dropping duplicates.
Remove the NaN values from the dataset
Cleaning individual columns.
Check for some more Transformations"""

'Deleting redundant columns.\nRenaming the columns.\nDropping duplicates.\nRemove the NaN values from the dataset\nCleaning individual columns.\nCheck for some more Transformations'

In [61]:
data

      transaction_hour merchant_category
0                   22       Electronics
1                    3            Travel
2                   17           Grocery
3                    4           Grocery
4                   15              Food
...                ...               ...
9995                22              Food
9996                 5          Clothing
9997                21       Electronics
9998                 2       Electronics
9999                 2          Clothing

[10000 rows x 2 columns]

# removing 1 by 1

In [62]:
data.rename(columns ={"transaction_hour":"transaction_hour1"})

      transaction_hour1 merchant_category
0                    22       Electronics
1                     3            Travel
2                    17           Grocery
3                     4           Grocery
4                    15              Food
...                 ...               ...
9995                 22              Food
9996                  5          Clothing
9997                 21       Electronics
9998                  2       Electronics
9999                  2          Clothing

[10000 rows x 2 columns]

In [65]:
data.columns

Index(['transaction_hour', 'merchant_category'], dtype='str')

In [67]:
data.columns[0].capitalize()

'Transaction_hour'

In [ ]:
for i in data.columns:
    print(i.capitalize())

Transaction_hour
Merchant_category

In [70]:
new_column_names = []
for i in data.columns:
     new_column_names.append(i.capitalize())

In [71]:
new_column_names

['Transaction_hour', 'Merchant_category']

In [72]:
data.columns = new_column_names

In [73]:
data.columns

Index(['Transaction_hour', 'Merchant_category'], dtype='str')

In [74]:
"""Deleting redundant columns.
Renaming the columns. -
Dropping duplicates.
Remove the NaN values from the dataset
Cleaning individual columns.
Check for some more Transformations"""

'Deleting redundant columns.\nRenaming the columns. -\nDropping duplicates.\nRemove the NaN values from the dataset\nCleaning individual columns.\nCheck for some more Transformations'

In [76]:
data.duplicated().sum()

np.int64(9880)

In [77]:
data.duplicated().value_counts()

True     9880
False     120
Name: count, dtype: int64

In [78]:
data.duplicated().tail(15)

9985    True
9986    True
9987    True
9988    True
9989    True
9990    True
9991    True
9992    True
9993    True
9994    True
9995    True
9996    True
9997    True
9998    True
9999    True
dtype: bool

In [80]:
data.drop_duplicates(inplace = True)

In [82]:
data.isna().sum()

Transaction_hour     0
Merchant_category    0
dtype: int64

In [83]:
data.dropna(inplace = True)

In [84]:
data.isna().sum()

Transaction_hour     0
Merchant_category    0
dtype: int64

In [86]:
data.reset_index(inplace=True)

In [87]:
data.drop(columns="index",inplace=True)

In [88]:
data

     Transaction_hour Merchant_category
0                  22       Electronics
1                   3            Travel
2                  17           Grocery
3                   4           Grocery
4                  15              Food
..                ...               ...
115                 8            Travel
116                 0            Travel
117                10            Travel
118                 2       Electronics
119                 2           Grocery

[120 rows x 2 columns]

In [ ]:
"""Deleting redundant columns.
Renaming the columns. -
Dropping duplicates.
Remove the NaN values from the dataset
Cleaning individual columns.
Check for some more Transformations"""

In [17]:
if "Rate" in data.columns:
    print(data["Rate"][14])
else:
    print("Column not found")

Column not found

In [95]:
data

     Transaction_hour Merchant_category
0                  22       Electronics
1                   3            Travel
2                  17           Grocery
3                   4           Grocery
4                  15              Food
..                ...               ...
115                 8            Travel
116                 0            Travel
117                10            Travel
118                 2       Electronics
119                 2           Grocery

[120 rows x 2 columns]

In [96]:
"""Deleting redundant columns.
Renaming the columns. -
Dropping duplicates.
Remove the NaN values from the dataset
Cleaning individual columns.
Check for some more Transformations"""

'Deleting redundant columns.\nRenaming the columns. -\nDropping duplicates.\nRemove the NaN values from the dataset\nCleaning individual columns.\nCheck for some more Transformations'

In [97]:
data

     Transaction_hour Merchant_category
0                  22       Electronics
1                   3            Travel
2                  17           Grocery
3                   4           Grocery
4                  15              Food
..                ...               ...
115                 8            Travel
116                 0            Travel
117                10            Travel
118                 2       Electronics
119                 2           Grocery

[120 rows x 2 columns]

In [98]:
data["Merchant_category"]

0      Electronics
1           Travel
2          Grocery
3          Grocery
4             Food
          ...
115         Travel
116         Travel
117         Travel
118    Electronics
119        Grocery
Name: Merchant_category, Length: 120, dtype: str

In [99]:
data["Merchant_category"].apply(lambda x: 1 if x == "Yes" else 0)

0      0
1      0
2      0
3      0
4      0
      ..
115    0
116    0
117    0
118    0
119    0
Name: Merchant_category, Length: 120, dtype: int64

In [100]:
data

     Transaction_hour Merchant_category
0                  22       Electronics
1                   3            Travel
2                  17           Grocery
3                   4           Grocery
4                  15              Food
..                ...               ...
115                 8            Travel
116                 0            Travel
117                10            Travel
118                 2       Electronics
119                 2           Grocery

[120 rows x 2 columns]

In [101]:
data.to_csv("Cleaned_csv_file.csv")

In [102]:
pd.read_csv("Cleaned_csv_file.csv")

     Unnamed: 0  Transaction_hour Merchant_category
0             0                22       Electronics
1             1                 3            Travel
2             2                17           Grocery
3             3                 4           Grocery
4             4                15              Food
..          ...               ...               ...
115         115                 8            Travel
116         116                 0            Travel
117         117                10            Travel
118         118                 2       Electronics
119         119                 2           Grocery

[120 rows x 3 columns]

In [103]:
data.to_csv("Cleaned_csv_file_no_index.csv",index = False)

In [104]:
pd.read_csv("Cleaned_csv_file_no_index.csv")

     Transaction_hour Merchant_category
0                  22       Electronics
1                   3            Travel
2                  17           Grocery
3                   4           Grocery
4                  15              Food
..                ...               ...
115                 8            Travel
116                 0            Travel
117                10            Travel
118                 2       Electronics
119                 2           Grocery

[120 rows x 2 columns]